const date = new Date()
let tahun = date.getFullYear()
let bulan = date.getMonth()
let dates = date.getDate()
let day = date.getDay()
let hours = date.getHours()
let minutes = date.getMinutes()
let seconds = date.getSeconds() 
let miliseconds = date.getMilliseconds()

console.log(date)
console.log("Tahun sekarang adalah " + tahun)
console.log("Bulan sekarang adalah " + bulan)
console.log("Tanggal sekarang adalah " + dates)
console.log("Hari sekarang adalah " + day.toString())
console.log("Jam sekarang adalah " + hours)
console.log("Menit sekarang adalah " + minutes)
console.log("Detik sekarang adalah " + seconds)
console.log("Milisecond sekarang adalah " + miliseconds)

